version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go test -v ./...
  test:
    docker:
      # specify the version
      - image: circleci/golang:1.9
        environment:
          GO111MODULE: "on"
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go test -v ./...
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          # only run this job if build succeeds
          requires:
            - build